import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

// ignore: sdk_version_set_literal
final icons = <IconData>{
  Icons.send,
  Icons.shopping_cart,
  Icons.shutter_speed,
  Icons.star,
  Icons.subway,
  Icons.supervised_user_circle,
  Icons.supervisor_account,
  Icons.surround_sound,
  Icons.sync,
  Icons.sync_problem,
  Icons.tap_and_play,
  Icons.terrain,
  Icons.text_fields,
  Icons.textsms,
  Icons.theaters,
  Icons.toys,
  Icons.track_changes,
  Icons.traffic,
  Icons.train,
  Icons.transfer_within_a_station,
  Icons.transform,
  Icons.translate,
  Icons.trip_origin,
  Icons.update,
  Icons.usb,
  Icons.verified_user,
  Icons.vibration,
  Icons.video_library,
  Icons.view_carousel,
  Icons.view_quilt,
  Icons.view_week,
  Icons.vignette,
  Icons.visibility,
  Icons.visibility_off,
  Icons.voice_chat,
  Icons.voicemail,
  Icons.volume_off,
  Icons.vpn_key,
  Icons.vpn_lock,
  Icons.wallpaper,
  Icons.warning,
  Icons.watch,
  Icons.wb_cloudy,
  Icons.wc,
  Icons.whatshot,
  Icons.widgets,
  Icons.wifi_lock,
  Icons.wifi_tethering,
  Icons.work,
  Icons.youtube_searched_for,
  Icons.zoom_out_map,
};